version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: confsearch
      POSTGRES_PASSWORD: confsearch
      POSTGRES_DB: confsearch
    ports:
      - "5432:5432"
