openapi: 3.0.3
info:
  title: Confsearch API
  version: 1.0.0

paths:
  /api/v1/search:
    get:
      summary: Search for conferences
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of conferences
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conference'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/events:
    get:
      summary: Get all events
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventWithTracks'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventWithTracks'
      responses:
        '201':
          description: Event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithTracks'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/events/{eventId}:
    get:
      summary: Get an event by ID
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Event details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithTracks'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventWithTracks'
      responses:
        '200':
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithTracks'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Event deleted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/conferences:
    get:
      summary: Get all conferences with their associated events
      responses:
        '200':
          description: List of conferences with events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConferenceWithEvents'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new conference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conference'
      responses:
        '201':
          description: Conference created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conference'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/conferences/{conferenceId}:
    get:
      summary: Get a conference by ID with associated events and event tracks
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Conference details with events and event tracks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConferenceWithEventsAndTracks'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update a conference
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conference'
      responses:
        '200':
          description: Conference updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conference'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a conference
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Conference deleted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Conference:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        acronym:
          type: string
        core_rank:
          type: string
        rank_source:
          type: string
        wikicfp_url:
          type: string
        website:
          type: string

    Event:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        conference:
          type: string
        acronym:
          type: string
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        categories:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        description:
          type: string
        paper_submission:
          type: string
          format: date-time
        abstract_submission:
          type: string
          format: date-time
        notification_due:
          type: string
          format: date-time
        final_due:
          type: string
          format: date-time
        camera_ready:
          type: string
          format: date-time
        deadline_notes:
          type: string
        wikicfp_url:
          type: string
        event_url:
          type: string
        submission_url:
          type: string
        location:
          type: string

    EventTrack:
      type: object
      properties:
        id:
          type: integer
        event_id:
          type: integer
        name:
          type: string
        description:
          type: string
        paper_submission:
          type: string
          format: date-time
        abstract_submission:
          type: string
          format: date-time
        notification_due:
          type: string
          format: date-time
        camera_ready_due:
          type: string
          format: date-time
        deadlines_note:
          type: string
          
    EventWithTracks:
      type: object
      allOf:
        - $ref: '#/components/schemas/Event'
        - type: object
          properties:
            tracks:
              type: array
              items:
                $ref: '#/components/schemas/EventTrack'

    ConferenceWithEvents:
      type: object
      allOf:
        - $ref: '#/components/schemas/Conference'
        - type: object
          properties:
            events:
              type: array
              items:
                $ref: '#/components/schemas/Event'

    ConferenceWithEventsAndTracks:
      type: object
      allOf:
        - $ref: '#/components/schemas/Conference'
        - type: object
          properties:
            events:
              type: array
              items:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Event'
                  - type: object
                    properties:
                      tracks:
                        type: array
                        items:
                          $ref: '#/components/schemas/EventTrack'

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
