openapi: 3.1.0
info:
  title: Confsearch API
  version: 1.0.3

paths:
  /api/v1/search:
    get:
      summary: Search for conferences
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConferenceListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/v1/events:
    get:
      summary: Get all events
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithTracksListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventWithTracks'
      responses:
        '201':
          description: Event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithTracksResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/events/{eventId}:
    get:
      summary: Get an event by ID
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithTracksResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventWithTracks'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithTracksResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/conferences:
    get:
      summary: Get all conferences with their associated events
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConferenceWithEventsListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create a new conference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conference'
      responses:
        '201':
          description: Conference created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConferenceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/v1/conferences/{conferenceId}:
    get:
      summary: Get a conference by ID with associated events and event tracks
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConferenceWithEventsAndTracksResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update a conference
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conference'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConferenceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a conference
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
        error:
          type: 'null'

    ConferenceResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Conference'
        error:
          type: 'null'

    ConferenceListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Conference'
        error:
          type: 'null'

    EventWithTracksResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/EventWithTracks'
        error:
          type: 'null'

    EventWithTracksListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/EventWithTracks'
        error:
          type: 'null'

    ConferenceWithEventsListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ConferenceWithEvents'
        error:
          type: 'null'

    ConferenceWithEventsAndTracksResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ConferenceWithEventsAndTracks'
        error:
          type: 'null'

    ErrorResponse:
      type: object
      properties:
        data:
          type: 'null'
        error:
          type: object
          properties:
            message:
              type: string
            code:
              type: integer

    Conference:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        acronym:
          type: string
        coreRank:
          type: string
        rankSource:
          type: string
        wikicfpUrl:
          type: string
        website:
          type: string

    Event:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        conference:
          type: string
        conferenceAcronym:
          type: string
        eventAcronym:
          type: string
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        categories:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        description:
          type: string
        paperSubmission:
          type: string
          format: date-time
        abstractSubmission:
          type: string
          format: date
        notificationDue:
          type: string
          format: date
        finalDue:
          type: string
          format: date
        cameraReady:
          type: string
          format: date
        deadlineNotes:
          type: string
        wikicfpUrl:
          type: string
        eventUrl:
          type: string
        submissionUrl:
          type: string
        location:
          type: string
        updatedAt:
          type: string
          format: date-time

    EventTrack:
      type: object
      properties:
        id:
          type: integer
        eventId:
          type: integer
        name:
          type: string
        description:
          type: string
        paperSubmission:
          type: string
          format: date
        abstractSubmission:
          type: string
          format: date
        notificationDue:
          type: string
          format: date
        cameraReadyDue:
          type: string
          format: date
        deadlinesNote:
          type: string
        isWorkshop:
          type: boolean

    EventWithTracks:
      type: object
      allOf:
        - $ref: '#/components/schemas/Event'
        - type: object
          properties:
            tracks:
              type: array
              items:
                $ref: '#/components/schemas/EventTrack'

    ConferenceWithEvents:
      type: object
      allOf:
        - $ref: '#/components/schemas/Conference'
        - type: object
          properties:
            events:
              type: array
              items:
                $ref: '#/components/schemas/Event'

    ConferenceWithEventsAndTracks:
      type: object
      allOf:
        - $ref: '#/components/schemas/Conference'
        - type: object
          properties:
            events:
              type: array
              items:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Event'
                  - type: object
                    properties:
                      tracks:
                        type: array
                        items:
                          $ref: '#/components/schemas/EventTrack'

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'