import { z } from "zod";

const categoryOptions = [
  "5G",
  "aerospace",
  "agents",
  "agriculture",
  "AI",
  "algorithms",
  "ambient intelligence",
  "analytics",
  "anthropology",
  "applications",
  "architecture",
  "art",
  "artificial intelligence",
  "artificial intelligene",
  "arts",
  "augmented reality",
  "automation",
  "big data",
  "bioinformatics",
  "biology",
  "biomedical",
  "biomedical engineering",
  "biometrics",
  "biotechnology",
  "blockchain",
  "business",
  "business intelligence",
  "business management",
  "cancer",
  "cardiology",
  "chemical",
  "chemical engineering",
  "chemistry",
  "circuits",
  "civil",
  "civil engineering",
  "climate change",
  "cloud",
  "cloud computing",
  "cognitive science",
  "collaboration",
  "communication",
  "communications",
  "compilers",
  "complexity",
  "computational biology",
  "computational intelligence",
  "computational linguistics",
  "computer",
  "computer architecture",
  "computer engineering",
  "computer graphics",
  "computer networks",
  "computer science",
  "computer security",
  "computer vision",
  "computing",
  "conference",
  "conferences",
  "control",
  "cryptography",
  "cultural studies",
  "culture",
  "cyber security",
  "cyber-physical systems",
  "cybersecurity",
  "data",
  "data analytics",
  "data management",
  "data mining",
  "data science",
  "database",
  "databases",
  "deep learning",
  "dependability",
  "design",
  "design automation",
  "development",
  "digital forensics",
  "digital humanities",
  "distributed computing",
  "distributed systems",
  "e-business",
  "e-commerce",
  "e-education",
  "e-health",
  "e-learning",
  "ecology",
  "ECONOMIC",
  "economics",
  "edge computing",
  "education",
  "ehealth",
  "elearning",
  "electrical",
  "electrical engineering",
  "electron devices",
  "electronics",
  "electronics engineering",
  "embedded systems",
  "energy",
  "engineering",
  "english",
  "entrepreneurship",
  "environment",
  "environmental",
  "environmental engineering",
  "environmental sciences",
  "ethics",
  "evolutionary computation",
  "film",
  "finance",
  "formal methods",
  "fuzzy systems",
  "games",
  "GIS",
  "graphics",
  "green computing",
  "grid computing",
  "HCI",
  "health",
  "health informatics",
  "healthcare",
  "high performance computing",
  "higher education",
  "history",
  "HPC",
  "human computer interaction",
  "human-computer interaction",
  "humanities",
  "ICT",
  "image processing",
  "industrial electronics",
  "industrial engineering",
  "industry",
  "informatics",
  "information",
  "information management",
  "information retrieval",
  "information science",
  "information security",
  "information system",
  "information systems",
  "information technology",
  "information theory",
  "innovation",
  "intelligent systems",
  "interdisciplinary",
  "international relations",
  "internet",
  "internet of things",
  "IOT",
  "IT",
  "knowledge discovery",
  "knowledge engineering",
  "knowledge management",
  "knowledge representation",
  "language",
  "law",
  "leadership",
  "learning",
  "life sciences",
  "linguistics",
  "linked data",
  "literature",
  "logic",
  "logistics",
  "machine learning",
  "management",
  "manufacturing",
  "marketing",
  "material science",
  "materials",
  "materials science",
  "mathematics",
  "measurement",
  "mechanical",
  "mechanical engineering",
  "mechatronics",
  "media",
  "medical",
  "medical imaging",
  "medicine",
  "mental health",
  "middleware",
  "mobile",
  "mobile computing",
  "mobility",
  "modeling",
  "modelling",
  "molecular biology",
  "multi-agent systems",
  "multidisciplinary",
  "multimedia",
  "music",
  "nanotechnology",
  "natural language processing",
  "network",
  "network security",
  "networking",
  "networks",
  "neural networks",
  "neurology",
  "neuroscience",
  "NLP",
  "nursing",
  "nutrition",
  "oncology",
  "ontologies",
  "ontology",
  "operating systems",
  "optics",
  "optimization",
  "parallel computing",
  "parallel processing",
  "pattern recognition",
  "pedagogy",
  "pediatrics",
  "performance",
  "pervasive computing",
  "philosophy",
  "photonics",
  "physics",
  "political science",
  "politics",
  "popular culture",
  "power",
  "power electronics",
  "power engineering",
  "privacy",
  "programming",
  "programming languages",
  "psychology",
  "public health",
  "recommender systems",
  "reliability",
  "religion",
  "remote sensing",
  "renewable energy",
  "research",
  "robotics",
  "safety",
  "science",
  "security",
  "security and privacy",
  "semantic web",
  "semantics",
  "sensor networks",
  "sensors",
  "services",
  "signal processing",
  "simulation",
  "smart cities",
  "smart grid",
  "social",
  "social computing",
  "social media",
  "social networks",
  "social science",
  "society",
  "sociology",
  "soft computing",
  "software",
  "software architecture",
  "software engineering",
  "software testing",
  "speech",
  "statistics",
  "sustainability",
  "sustainable development",
  "systems",
  "systems engineering",
  "teaching",
  "technologies",
  "technology",
  "telecommunication",
  "testing",
  "text mining",
  "theoretical computer science",
  "theory",
  "tourism",
  "training",
  "trainings",
  "transportation",
  "trust",
  "ubiquitous computing",
  "verification",
  "virtual reality",
  "visualization",
  "VLSI",
  "web",
  "web services",
  "wireless",
  "wireless communication",
] as const;

type Category = (typeof categoryOptions)[number];

const normalizeString = (s: string): string => s.toLowerCase().trim().replace(/\s+/g, " ");

const transformCategory = (input: string): Category | null => {
  const normalized = normalizeString(input);
  const match = categoryOptions.find((option) => normalizeString(option) === normalized);
  return match || null;
};

export const categoriesSchema = z
  .array(z.string())
  .transform((categories) =>
    categories.map(transformCategory).filter((category): category is Category => category !== null),
  );
