name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Trigger deployment
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_BASIC_AUTH }}
        run: |
          if [ -z "$DEPLOY_URL" ] || [ -z "$DEPLOY_TOKEN" ]; then
            echo "Error: DEPLOY_URL or DEPLOY_TOKEN is not set"
            exit 1
          fi
          
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $DEPLOY_TOKEN" \
            "$DEPLOY_URL")
          
          if [ "$response" -eq 200 ]; then
            echo "Deployment triggered successfully"
          else
            echo "Error: Deployment failed with status code $response"
            exit 1
          fi